name: micro2025-baseline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - wget=1.21.4
  - pip
  - requests=2.32.2
  - numpy=1.26.4
  - scipy=1.13.1
  - matplotlib=3.8.4
  - pandas=2.2.1
  - flake8=7.0.0
  - pylint=3.2.2
  - autopep8=2.0.4
  - pip:
    - conda-lock==1.4
